#!/bin/bash

# Generate Training Data for Action Planner from ImageAgent Results
# Reads action_plan.json files generated by 30B during imageagent pipeline

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$(dirname "$SCRIPT_DIR")")"

# ============================================================================
# Configuration
# ============================================================================

# Default paths
DEFAULT_RESULTS_DIR="$PROJECT_ROOT/imageagent_results_40000_no_cot"
DEFAULT_OUTPUT_DIR="$PROJECT_ROOT/training_data_40000_no_cot/standard"
DEFAULT_EXCLUDE_FILE="$PROJECT_ROOT/test_samples.txt"

# Training data configuration
NUM_DATAPOINTS=20000         # 20K samples from 39,600 available training samples
RL_MODE=false               # Set to true to enable RL filtering
RL_THRESHOLD=3.5            # Minimum reward score for RL filtering
RL_METRIC="overall_quality" # Metric to use: overall_quality, action_plan_quality, etc.

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
NC='\033[0m'

# ============================================================================
# Helper Functions
# ============================================================================

print_color() {
    local color=$1
    local message=$2
    echo -e "${color}${message}${NC}"
}

show_usage() {
    echo "Generate Training Data for Action Planner from ImageAgent Results"
    echo "=================================================================="
    echo ""
    echo "Usage: $0 [OPTIONS]"
    echo ""
    echo "This script reads action_plan.json files and creates training data."
    echo ""
    echo "Options:"
    echo "  -i, --input DIR         Input imageagent_results directory"
    echo "  -o, --output DIR        Output directory for training data"
    echo "  -n, --num-datapoints N  Number of samples to include (default: all)"
    echo "  --rl                    Enable RL filtering mode"
    echo "  --threshold FLOAT       Minimum reward score for RL (default: 4.0)"
    echo "  --metric STRING         Reward metric to use (default: overall_quality)"
    echo "  -h, --help              Show this help message"
    echo ""
    echo "Examples:"
    echo "  $0                                    # Use default paths"
    echo "  $0 -i ./my_results                    # Specify custom input"
    echo "  $0 -o ./training_data                 # Specify custom output"
    echo ""
    echo "Note: Uses Qwen3-VL-30B-A3B-Thinking as teacher to generate ground truth"
    echo ""
}

# ============================================================================
# Parse Arguments
# ============================================================================

RESULTS_DIR="$DEFAULT_RESULTS_DIR"
OUTPUT_DIR="$DEFAULT_OUTPUT_DIR"
EXCLUDE_FILE="$DEFAULT_EXCLUDE_FILE"

while [[ $# -gt 0 ]]; do
    case $1 in
        -i|--input)
            RESULTS_DIR="$2"
            shift 2
            ;;
        -o|--output)
            OUTPUT_DIR="$2"
            shift 2
            ;;
        -n|--num-datapoints)
            NUM_DATAPOINTS="$2"
            shift 2
            ;;
        --exclude-file)
            EXCLUDE_FILE="$2"
            shift 2
            ;;
        --rl)
            RL_MODE=true
            shift
            ;;
        --threshold)
            RL_THRESHOLD="$2"
            shift 2
            ;;
        --metric)
            RL_METRIC="$2"
            shift 2
            ;;
        -h|--help)
            show_usage
            exit 0
            ;;
        *)
            print_color $RED "❌ Unknown option: $1"
            show_usage
            exit 1
            ;;
    esac
done

# ============================================================================
# Validation
# ============================================================================

print_color $PURPLE "============================================================================"
print_color $PURPLE "📊 Generate Training Data for Action Planner"
print_color $PURPLE "============================================================================"
echo ""

# Check input directory
if [ ! -d "$RESULTS_DIR" ]; then
    print_color $RED "❌ Input directory not found: $RESULTS_DIR"
    exit 1
fi

print_color $GREEN "✓ Input directory: $RESULTS_DIR"
print_color $CYAN "📁 Output directory: $OUTPUT_DIR"

# Show configuration
if [ -n "$NUM_DATAPOINTS" ]; then
    print_color $CYAN "📊 Max samples: $NUM_DATAPOINTS"
fi

if [ "$RL_MODE" = true ]; then
    print_color $YELLOW "🏆 RL Mode: Filtering by $RL_METRIC >= $RL_THRESHOLD"
fi

# Count available samples with action_plan.json
NUM_SAMPLES=$(find "$RESULTS_DIR" -type f -name "action_plan.json" | wc -l)
print_color $CYAN "📸 Found $NUM_SAMPLES folders with action_plan.json"

if [ "$NUM_SAMPLES" -eq 0 ]; then
    print_color $RED "❌ No action_plan.json files found!"
    print_color $YELLOW "💡 Make sure you ran imageagent pipeline with --use-30b flag"
    exit 1
fi

echo ""

# ============================================================================
# Environment Setup
# ============================================================================

print_color $BLUE "🔧 Setting up environment..."

# Activate conda environment
if [ -f ~/miniconda3/etc/profile.d/conda.sh ]; then
    source ~/miniconda3/etc/profile.d/conda.sh
    conda activate img-agent || {
        print_color $YELLOW "⚠️  Could not activate img-agent, using system Python"
    }
elif [ -f ~/anaconda3/etc/profile.d/conda.sh ]; then
    source ~/anaconda3/etc/profile.d/conda.sh
    conda activate img-agent || {
        print_color $YELLOW "⚠️  Could not activate img-agent, using system Python"
    }
fi

PYTHON_PATH=$(which python)
print_color $GREEN "✓ Using Python: $PYTHON_PATH"
echo ""

# ============================================================================
# Generate Data
# ============================================================================

print_color $PURPLE "🚀 Generating Training Data..."
echo ""

cd "$PROJECT_ROOT"

# Build command (reads action_plan.json from disk)
CMD="python scripts/generate_planner_training_data.py \"$RESULTS_DIR\" --output-dir \"$OUTPUT_DIR\""

# Add optional arguments
if [ -n "$NUM_DATAPOINTS" ]; then
    CMD="$CMD --num-datapoints $NUM_DATAPOINTS"
fi

if [ -n "$EXCLUDE_FILE" ] && [ -f "$EXCLUDE_FILE" ]; then
    CMD="$CMD --exclude-file \"$EXCLUDE_FILE\""
    print_color $CYAN "📝 Excluding test samples from: $EXCLUDE_FILE"
fi

if [ "$RL_MODE" = true ]; then
    CMD="$CMD --rl-data --threshold $RL_THRESHOLD --reward-metric $RL_METRIC"
fi

print_color $BLUE "Executing: $CMD"
echo ""

eval $CMD

EXIT_CODE=$?

# ============================================================================
# Results
# ============================================================================

echo ""

if [ $EXIT_CODE -eq 0 ]; then
    print_color $GREEN "============================================================================"
    print_color $GREEN "🎉 Training Data Generation Complete!"
    print_color $GREEN "============================================================================"
    echo ""
    
    # Check output file
    OUTPUT_FILE="$OUTPUT_DIR/planner_training_data.json"
    if [ -f "$OUTPUT_FILE" ]; then
        FILE_SIZE=$(du -h "$OUTPUT_FILE" | cut -f1)
        NUM_LINES=$(wc -l < "$OUTPUT_FILE")
        
        print_color $CYAN "📄 Output file: $OUTPUT_FILE"
        print_color $CYAN "📦 File size: $FILE_SIZE"
        print_color $CYAN "📏 Lines: $NUM_LINES"
        
        # Try to count samples in JSON
        if command -v jq >/dev/null 2>&1; then
            SAMPLE_COUNT=$(jq 'length' "$OUTPUT_FILE")
            print_color $CYAN "🎯 Total samples: $SAMPLE_COUNT"
        fi
    fi
    
    echo ""
    print_color $PURPLE "Next steps:"
    print_color $PURPLE "  1. Review training data: cat $OUTPUT_FILE | jq '.[] | .user_prompt' | head"
    print_color $PURPLE "  2. Start planner training: ./scripts/start_planner_training.sh"
    
else
    print_color $RED "============================================================================"
    print_color $RED "❌ Training Data Generation Failed"
    print_color $RED "============================================================================"
    print_color $YELLOW "Check logs above for errors"
    exit $EXIT_CODE
fi



