"""
Generate Planner Training Data from ImageAgent Results

This script creates training data for the Qwen3-VL-4B action planner by:
1. Reading existing imageagent_results data (with action_plan.json from 30B)
2. Creating supervised training examples: (image, user_prompt) → action_plan.json

The action_plan.json files are already generated by the 30B model during
the imageagent pipeline execution (with --use-30b flag).

Training format for Qwen3-VL:
{
  "image": "path/to/original.png",
  "user_prompt": "User editing request",
  "target_action_plan": {
    "overall_instruction": "...",
    "actions": [...]
  }
}
"""

import os
import sys
import json
import argparse
from pathlib import Path
from typing import Dict, List, Any, Optional

# Add project root to path
SCRIPT_DIR = Path(__file__).parent.resolve()
PROJECT_ROOT = SCRIPT_DIR.parent.resolve()
sys.path.insert(0, str(PROJECT_ROOT))


def process_imageagent_results(
    results_dir: str,
    output_dir: str,
    num_datapoints: int = None,
    rl_data: bool = False,
    threshold: float = 4.0,
    reward_metric: str = "overall_quality",
    exclude_file: str = None
) -> None:
    """
    Process imageagent results and create planner training data.
    
    Args:
        results_dir: Directory containing imageagent results (with action_plan.json)
        output_dir: Directory to save planner training data
        num_datapoints: Number of samples to include (None = all)
        rl_data: Enable RL filtering based on reward scores
        threshold: Minimum reward score for RL filtering
        reward_metric: Which reward metric to use for filtering
        exclude_file: Path to file containing sample IDs to exclude (one per line)
    """
    print("=" * 60)
    print("📚 Processing ImageAgent Results for Planner Training")
    print("=" * 60)
    print(f"Input: {results_dir}")
    print(f"Output: {output_dir}")
    if rl_data:
        print(f"🏆 RL Mode: Filtering by {reward_metric} >= {threshold}")
    if num_datapoints:
        print(f"📊 Max samples: {num_datapoints}")
    print()
    
    # Load excluded sample IDs if provided
    excluded_ids = set()
    if exclude_file and os.path.exists(exclude_file):
        with open(exclude_file, 'r') as f:
            excluded_ids = set(line.strip() for line in f if line.strip())
        print(f"🚫 Excluding {len(excluded_ids)} test samples from: {exclude_file}")
        print()
    
    # Create output directory
    os.makedirs(output_dir, exist_ok=True)
    
    # Find all folders with required files
    results_path = Path(results_dir).resolve()
    training_samples = []
    skipped_count = 0
    excluded_count = 0
    
    # Iterate through all subdirectories
    for folder in sorted(results_path.iterdir()):
        if not folder.is_dir():
            continue
        
        # Skip if in exclusion list (test samples)
        if folder.name in excluded_ids:
            excluded_count += 1
            continue
        
        # Check for required files
        original_path = folder / "original.png"
        action_plan_path = folder / "action_plan.json"
        prompt_path = folder / "prompt.json"
        
        # Skip if missing required files
        if not original_path.exists():
            continue
        
        if not action_plan_path.exists():
            skipped_count += 1
            continue
        
        if not prompt_path.exists():
            continue
        
        # Load prompt (contains user's transformation request)
        try:
            with open(prompt_path, 'r') as f:
                prompt_data = json.load(f)
            
            # Extract user prompt from edit section (support both edit_info and edit)
            if 'edit_info' in prompt_data and 'text' in prompt_data['edit_info']:
                user_prompt = prompt_data['edit_info']['text']
            elif 'edit' in prompt_data and 'text' in prompt_data['edit']:
                user_prompt = prompt_data['edit']['text']
            else:
                print(f"⚠️  Skipping {folder.name}: No edit prompt found")
                skipped_count += 1
                continue
            
            # Load action plan (ground truth from 30B)
            with open(action_plan_path, 'r') as f:
                action_plan = json.load(f)
            
            # Create training sample
            analysis_path = folder / "analysis.json"
            sample = {
                "id": folder.name,  # Unique ID for cached training
                "image_path": str(original_path.relative_to(PROJECT_ROOT)),
                "analysis_path": str(analysis_path.relative_to(PROJECT_ROOT)),  # For end-to-end evaluation
                "user_prompt": user_prompt,
                "target_action_plan": action_plan,
                "metadata": {
                    "source_dir": str(folder.relative_to(PROJECT_ROOT)),
                    "folder_name": folder.name
                }
            }
            
            # If RL mode, load and check reward score
            if rl_data:
                reward_path = folder / "reward_scores.json"
                if not reward_path.exists():
                    print(f"⚠️  Skipping {folder.name}: No reward_scores.json")
                    skipped_count += 1
                    continue
                
                with open(reward_path, 'r') as f:
                    reward_data = json.load(f)
                
                # Check threshold
                if reward_metric not in reward_data["scores"]:
                    print(f"⚠️  Skipping {folder.name}: Missing metric {reward_metric}")
                    skipped_count += 1
                    continue
                
                score = reward_data["scores"][reward_metric]["score"]
                if score < threshold:
                    skipped_count += 1
                    continue  # Skip low-quality samples
                
                # Add reward info to sample
                sample["reward_score"] = score
                sample["reward_scores"] = reward_data["scores"]
            
            training_samples.append(sample)
            
            if len(training_samples) % 100 == 0:
                print(f"  ✓ Processed {len(training_samples)} samples...")
        
        except Exception as e:
            print(f"⚠️  Error processing {folder.name}: {str(e)}")
            skipped_count += 1
            continue
    
    # Apply sampling if num_datapoints specified
    if num_datapoints and len(training_samples) > num_datapoints:
        if rl_data:
            # RL mode: Sort by score and take top N
            training_samples.sort(key=lambda x: x["reward_score"], reverse=True)
            training_samples = training_samples[:num_datapoints]
            print(f"\n📊 Selected top {num_datapoints} samples by {reward_metric}")
        else:
            # Uniform mode: Random sampling
            import random
            random.seed(42)
            training_samples = random.sample(training_samples, num_datapoints)
            print(f"\n📊 Uniformly sampled {num_datapoints} samples")
    
    # Save training data
    output_file = Path(output_dir) / "planner_training_data.json"
    
    description = "Planner training data with ground truth action plans"
    if rl_data:
        description += f" (RL-filtered: {reward_metric} >= {threshold})"
    
    training_data = {
        "version": "3.0",
        "description": description,
        "total_samples": len(training_samples),
        "rl_filtered": rl_data,
        "samples": training_samples
    }
    
    with open(output_file, 'w', encoding='utf-8') as f:
        json.dump(training_data, f, indent=2, ensure_ascii=False)
    
    # Print summary
    print()
    print()
    print("=" * 60)
    print("✅ Training Data Generation Complete!")
    print("=" * 60)
    print(f"📊 Total samples: {len(training_samples)}")
    if excluded_count > 0:
        print(f"🚫 Excluded (test set): {excluded_count}")
    print(f"⚠️  Skipped folders: {skipped_count}")
    if rl_data:
        print(f"🏆 RL filtering: {reward_metric} >= {threshold}")
        if training_samples:
            avg_score = sum(s["reward_score"] for s in training_samples) / len(training_samples)
            print(f"📈 Average {reward_metric}: {avg_score:.2f}")
    print(f"💾 Output file: {output_file}")
    print()
    
    if len(training_samples) == 0:
        print("❌ ERROR: No valid training samples found!")
        if rl_data:
            print(f"💡 Try lowering --threshold (current: {threshold})")
        else:
            print("💡 Make sure action_plan.json files exist")
        sys.exit(1)


def main():
    parser = argparse.ArgumentParser(
        description="Generate planner training data from imageagent results"
    )
    
    parser.add_argument(
        "results_dir",
        help="Directory containing imageagent results (with action_plan.json files)"
    )
    
    parser.add_argument(
        "--output-dir",
        default="./training_data/standard",
        help="Output directory for training data (default: ./training_data/standard)"
    )
    
    parser.add_argument(
        "--num-datapoints",
        type=int,
        default=None,
        help="Number of samples to include (uniform sampling or RL filtering)"
    )
    
    parser.add_argument(
        "--rl-data",
        action="store_true",
        help="Enable RL filtering based on reward scores"
    )
    
    parser.add_argument(
        "--threshold",
        type=float,
        default=4.0,
        help="Minimum reward score for RL filtering (default: 4.0)"
    )
    
    parser.add_argument(
        "--reward-metric",
        type=str,
        default="overall_quality",
        choices=["overall_quality", "action_plan_quality", "adherence_to_prompt", 
                 "adherence_to_plan", "plan_reasoning", "final_image_quality"],
        help="Which reward metric to use for filtering (default: overall_quality)"
    )
    
    parser.add_argument(
        "--exclude-file",
        type=str,
        default=None,
        help="Path to file containing sample IDs to exclude (e.g., test_samples.txt)"
    )
    
    args = parser.parse_args()
    
    # Validate input directory
    if not os.path.exists(args.results_dir):
        print(f"❌ Error: Results directory not found: {args.results_dir}")
        sys.exit(1)
    
    # Process results
    process_imageagent_results(
        results_dir=args.results_dir,
        output_dir=args.output_dir,
        num_datapoints=args.num_datapoints,
        rl_data=args.rl_data,
        threshold=args.threshold,
        reward_metric=args.reward_metric,
        exclude_file=args.exclude_file
    )


if __name__ == "__main__":
    main()
